[package]
name = "actor_with_llm_prototype"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cargo-steady-state = "0.2.5"
encoding_rs = "0.8.35"
llama-cpp-2 = "0.1.124"
libc = "0.2"